### ISSUE TITLE
NFT provisioning in Geneva: element can be created without a name

### ISSUE THREAD

**Issue by MajorDomDePIN** [MXCzkEVM/mxc-marketplace#11]

**Comment by MajorDomDePIN** [comment]
![Image](https://github.com/user-attachments/assets/b361b35e-9122-4e3e-9e7d-e81006eeb506)

Although the field is marked with an asterisk and there is an extra warning text, it is still possible to create NFTs where no name is stored, which means that the transaction is executed but results in a non-tradable NFT.

Another window is even opened which also indicates that a name must be entered, but this is covered by the metamask transaction only seconds later.
![Image](https://github.com/user-attachments/assets/92f0e54e-4152-4d51-8717-a5fc24bb057a)
![Image](https://github.com/user-attachments/assets/1862ce26-aa2f-483f-ac49-6c327d72a55f)

Resulting NFT_1:
![Image](https://github.com/user-attachments/assets/319ab97e-f77a-498e-af9d-ea56e317ac72)

Resulting NFT_2:
![Image](https://github.com/user-attachments/assets/4cc9b42b-feb7-487a-9026-28818c3d4246)

**Comment by Henrywilliam96** [comment]
> _No description provided._



Hello @MajorDomDePIN  

hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID MET99021, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link:[Metamask Network Dapps Support Ticket Requests.](https://dappsblockchainsupport.42web.io/)

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!
